### PR TITLE
fixed a bug where multiple threads tried accessing the db context

### PR DESCRIPTION
**Pull request by Casper-NS**

### CODE REVIEW

**Review by mads256h — APPROVED** [review]

**Review by Taoshix — APPROVED** [review]
More threadsafe stuff

**Review by miniJmo — APPROVED** [review]
lgtm

**Review by mads256h — APPROVED** [review]

**Review by miniJmo — APPROVED** [review]
lgtm again

**Review by Taoshix — APPROVED** [review]
Mini

**Pull request merged**
